"""Module containing document service implementation."""

from io import BytesIO
from pathlib import Path
from typing import Iterable
from uuid import UUID
from PyPDF2 import PdfReader

from src.core.domain.document import Document, DocumentBroker
from src.core.repositories.idocument import IDocumentRepository
from src.core.repositories.iproject import IProjectRepository
from src.infrastructure.services.idocument import IDocumentService

ALLOWED_EXTENSIONS = {".pdf", ".txt"}


class InvalidFileFormatError(ValueError):
    """Raised when a file format is not supported."""


class DocumentService(IDocumentService):
    """A class implementing the document service.

    All access control logic is here — router is thin.
    Authorization is based on project ownership:
    - Owner of project → full CRUD on documents
    - Non-owner → read only if is_public = true
    - Non-owner write attempt → None/False (resource masking → 404)
    """

    _repository: IDocumentRepository
    _project_repository: IProjectRepository

    def __init__(
        self,
        repository: IDocumentRepository,
        project_repository: IProjectRepository,
    ) -> None:
        self._repository = repository
        self._project_repository = project_repository

    async def _is_project_owner(self, project_id: int, user_id: str) -> bool:
        """Check if the user is the owner of the project.

        Args:
            project_id (int): The project id.
            user_id (str): The UUID of the user.

        Returns:
            bool: True if the user owns the project.
        """

        project = await self._project_repository.get_by_id(project_id)

        if project is None:
            return False

        return str(dict(project)["user_id"]) == user_id

    async def _get_project_owner_id(self, project_id: int) -> str | None:
        """Get the owner UUID of a project.

        Args:
            project_id (int): The project id.

        Returns:
            str | None: The owner UUID or None if project not found.
        """

        project = await self._project_repository.get_by_id(project_id)

        if project is None:
            return None

        return str(dict(project)["user_id"])

    @staticmethod
    def _validate_file_extension(filename: str) -> str:
        """Validate that the file extension is allowed.

        Args:
            filename (str): The original filename.

        Returns:
            str: The validated lowercase extension.

        Raises:
            InvalidFileFormatError: If the extension is not PDF or TXT.
        """

        ext = Path(filename).suffix.lower()

        if ext not in ALLOWED_EXTENSIONS:
            raise InvalidFileFormatError(
                f"Niedozwolony format pliku: {ext}. Dozwolone: PDF, TXT"
            )

        return ext

    @staticmethod
    def _extract_text(file_content: bytes, extension: str) -> str:
        """Extract text content from file bytes.

        Args:
            file_content (bytes): The raw file content.
            extension (str): The file extension (.pdf or .txt).

        Returns:
            str: The extracted text.

        Raises:
            InvalidFileFormatError: If text extraction fails.
        """

        if extension == ".txt":
            return file_content.decode("utf-8")

        if extension == ".pdf":

            reader = PdfReader(BytesIO(file_content))
            text_parts = []

            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text_parts.append(page_text)

            return "\n".join(text_parts)

        raise InvalidFileFormatError(
            f"Nie można wyodrębnić tekstu z formatu: {extension}"
        )

    async def create_document(
        self,
        project_id: int,
        filename: str,
        file_content: bytes,
        is_public: bool,
        user_id: str,
    ) -> Document:
        """Create a new document for the given project.

        Only the project owner can create documents.
        Validates the file format, extracts text content,
        and persists the document. public_id is generated by the database.

        Args:
            project_id (int): The id of the parent project.
            filename (str): The original filename.
            file_content (bytes): The raw file content.
            is_public (bool): Whether the document is publicly visible.
            user_id (str): The UUID of the requesting user.

        Returns:
            Document: The created document details.

        Raises:
            InvalidFileFormatError: If the file format is not supported.
            LookupError: If the project does not exist or user is not owner.
        """

        if not await self._is_project_owner(project_id, user_id):
            raise LookupError("Project not found")

        ext = self._validate_file_extension(filename)
        text = self._extract_text(file_content, ext)

        name = Path(filename).stem[:255]

        broker = DocumentBroker(
            name=name,
            data=text,
            is_public=is_public,
            project_id=project_id,
        )

        record = await self._repository.add_document(broker)

        return Document(**dict(record))

    async def get_document(
        self,
        public_id: UUID,
        user_id: str,
    ) -> Document | None:
        """Get a document by public UUID with access control.

        Owner of the parent project always sees the document.
        Non-owner sees it only when is_public is true.
        Otherwise returns None (resource masking → 404).

        Args:
            public_id (UUID): The public UUID of the document.
            user_id (str): The UUID of the requesting user.

        Returns:
            Document | None: The document if accessible, None otherwise.
        """

        record = await self._repository.get_by_public_id(public_id)

        if record is None:
            return None

        record_dict = dict(record)
        owner_id = await self._get_project_owner_id(record_dict["project_id"])

        if owner_id is None:
            return None

        if owner_id != user_id and not record_dict["is_public"]:
            return None

        return Document(**record_dict)

    async def get_project_documents(
        self,
        project_id: int,
        user_id: str,
    ) -> Iterable[Document]:
        """Get documents for a project with access control.

        Owner of the project sees all documents.
        Non-owner sees only documents with is_public = true.

        Args:
            project_id (int): The id of the project.
            user_id (str): The UUID of the requesting user.

        Returns:
            Iterable[Document]: The visible documents.
        """

        project = await self._project_repository.get_by_id(project_id)

        if project is None:
            return []

        is_owner = str(dict(project)["user_id"]) == user_id

        if is_owner:
            records = await self._repository.get_by_project(project_id)
        else:
            records = await self._repository.get_public_by_project(project_id)

        return [Document(**dict(r)) for r in records]

    async def update_document(
        self,
        public_id: UUID,
        user_id: str,
        filename: str | None = None,
        file_content: bytes | None = None,
        name: str | None = None,
        is_public: bool | None = None,
    ) -> Document | None:
        """Update a document by public UUID. Only project owner can update.

        Non-owner receives None (resource masking → 404).
        Supports partial update of name, is_public, and file re-upload.
        project_id cannot be changed.

        Args:
            public_id (UUID): The public UUID of the document.
            user_id (str): The UUID of the requesting user.
            filename (str | None): New filename if re-uploading.
            file_content (bytes | None): New file content if re-uploading.
            name (str | None): New document name.
            is_public (bool | None): New visibility setting.

        Returns:
            Document | None: The updated document if authorized, None otherwise.

        Raises:
            InvalidFileFormatError: If the new file format is not supported.
        """

        record = await self._repository.get_by_public_id(public_id)

        if record is None:
            return None

        record_dict = dict(record)

        if not await self._is_project_owner(record_dict["project_id"], user_id):
            return None

        values = {}

        if file_content is not None and filename is not None:
            ext = self._validate_file_extension(filename)
            values["data"] = self._extract_text(file_content, ext)

        if name is not None:
            values["name"] = name

        if is_public is not None:
            values["is_public"] = is_public

        if not values:
            return Document(**record_dict)

        updated = await self._repository.update_document(
            record_dict["id"], values
        )

        if updated is None:
            return None

        return Document(**dict(updated))

    async def delete_document(self, public_id: UUID, user_id: str) -> bool:
        """Delete a document by public UUID. Only project owner can delete.

        Non-owner receives False (resource masking → 404).

        Args:
            public_id (UUID): The public UUID of the document.
            user_id (str): The UUID of the requesting user.

        Returns:
            bool: True if deleted, False if not found or not authorized.
        """

        record = await self._repository.get_by_public_id(public_id)

        if record is None:
            return False

        record_dict = dict(record)

        if not await self._is_project_owner(record_dict["project_id"], user_id):
            return False

        return await self._repository.delete_document(record_dict["id"])
