"""A repository for document entity."""

from typing import Any, Iterable
from uuid import UUID

from src.core.domain.document import DocumentBroker
from src.core.repositories.idocument import IDocumentRepository
from src.db import database, document_table


class DocumentRepository(IDocumentRepository):
    """An implementation of repository class for document."""

    async def get_by_id(self, document_id: int) -> Any | None:
        """Get a single document by its internal id.

        Args:
            document_id (int): The internal document id.

        Returns:
            Any | None: The document if found.
        """

        query = document_table \
            .select() \
            .where(document_table.c.id == document_id)

        return await database.fetch_one(query)

    async def get_by_public_id(self, public_id: UUID) -> Any | None:
        """Get a single document by its public UUID.

        Args:
            public_id (UUID): The public UUID of the document.

        Returns:
            Any | None: The document if found.
        """

        query = document_table \
            .select() \
            .where(document_table.c.public_id == public_id)

        return await database.fetch_one(query)

    async def get_by_project(self, project_id: int) -> Iterable[Any]:
        """Get all documents belonging to a project.

        Args:
            project_id (int): The project id.

        Returns:
            Iterable[Any]: The collection of project documents.
        """

        query = document_table \
            .select() \
            .where(document_table.c.project_id == project_id)

        return await database.fetch_all(query)

    async def get_public_by_project(self, project_id: int) -> Iterable[Any]:
        """Get public documents belonging to a project.

        Args:
            project_id (int): The project id.

        Returns:
            Iterable[Any]: The collection of public project documents.
        """

        query = document_table \
            .select() \
            .where(
                (document_table.c.project_id == project_id)
                & (document_table.c.is_public == True)
            )

        return await database.fetch_all(query)

    async def add_document(self, data: DocumentBroker) -> Any | None:
        """Add a new document. public_id is generated by the database.

        Args:
            data (DocumentBroker): The document data.

        Returns:
            Any | None: The newly created document.
        """

        query = document_table.insert().values(**data.model_dump())
        last_record_id = await database.execute(query)

        return await self.get_by_id(last_record_id)

    async def update_document(
        self,
        document_id: int,
        values: dict,
    ) -> Any | None:
        """Update an existing document by internal id.

        Args:
            document_id (int): The internal document id.
            values (dict): The fields to update.

        Returns:
            Any | None: The updated document.
        """

        query = document_table \
            .update() \
            .where(document_table.c.id == document_id) \
            .values(**values)

        await database.execute(query)

        return await self.get_by_id(document_id)

    async def delete_document(self, document_id: int) -> bool:
        """Delete a document by internal id.

        Args:
            document_id (int): The internal document id.

        Returns:
            bool: Success of the operation.
        """

        if not await self.get_by_id(document_id):
            return False

        query = document_table \
            .delete() \
            .where(document_table.c.id == document_id)

        await database.execute(query)

        return True
